### ISSUE TITLE
Broken link on web page

### ISSUE THREAD

**Issue by martinjuckes** [Llannelongue/GreenAlgorithms4HPC#2]
Apologies if this is the wrong place to raise this:

The https://www.lannelongue.eu/research/green-algorithms/ page has a link to ` a practical online tool ' which directs to `https://www.lannelongue.eu/research/green-algorithms/www.green-algorithms.org`. I think it should be `https://www.green-algorithms.org`.

**Comment by Llannelongue** [comment]
Very true, good catch, thank you!
