### ISSUE TITLE
Could be possible to input data using a csv

### ISSUE THREAD

**Issue by edgano** [Llannelongue/GreenAlgorithms4HPC#4]
Hi, I would like to know if it's possible to feed the algorithm with a custom csv.

The default csv I have looks like

```
task_id	hash	native_id	name	status	exit	submit	duration	realtime	%cpu	peak_rss	peak_vmem	rchar	wchar
2	17/8fd00a	453454	sayHello (2)	COMPLETED	0	2022-08-03 13:17:35.534	4.5s	0ms	21.0%	0	0	64.8 KB	1.4 KB
4	42/f8a041	453455	sayHello (4)	COMPLETED	0	2022-08-03 13:17:35.707	4.3s	0ms	27.0%	0	0	64.9 KB	1.4 KB
1	11/e8ccd6	453456	sayHello (1)	COMPLETED	0	2022-08-03 13:17:35.881	4.2s	0ms	0.0%	0	0	64.9 KB	1.4 KB
3	bc/af946e	453457	sayHello (3)	COMPLETED	0	2022-08-03 13:17:36.049	4s	0ms	21.1%	0	0	64.9 KB	1.4 KB
```

I know it will be needed to add more data (model, PUE, etc.)

thanks in advance !

**Comment by Llannelongue** [comment]
Yes! You can use the command `--useLoggedOutput <path_to_file>`, you just need to make sure it looks like a slurm output. You can see how it's being used [here](https://github.com/Llannelongue/GreenAlgorithms4HPC/blob/f8d5c630a3a057ed76e7ad0e56bb3974f8e17fa4/GreenAlgorithms_workloadManager.py#L241). 
(It was meant as only a debugging tool, but maybe I should include it as a standard option!)

**Comment by Llannelongue** [comment]
It is now an option available by default, and has been renamed `--useCustomLogs` (with [release 0.2.2](https://github.com/Llannelongue/GreenAlgorithms4HPC/releases/tag/v0.2.2-beta)). It is also possible to specify a full path (instead of having to put the csv in a specific folder).
